CREATE TABLE job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    platform VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE search_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE search_keywords (
    criteria_id BIGINT NOT NULL,
    keyword VARCHAR(255),
    FOREIGN KEY (criteria_id) REFERENCES search_criteria(id)
);

CREATE TABLE search_locations (
    criteria_id BIGINT NOT NULL,
    location VARCHAR(255),
    FOREIGN KEY (criteria_id) REFERENCES search_criteria(id)
);
